---
title: "Hello, World!"
---

... and welcome to my personal website! Here you can find an HTML iteration of my [résumé](resume.html), though feel free to use the envelope icon in the navigation bar to shoot me an email and request a PDF copy. I am also always happy to chat about mathematics, Florence + the Machine, and any and all cheeses, so don't hesitate to drop a line!

You can also find a [dashboard](dashboard.html) highlighting some data from _The Instacart Online Grocery Shopping Dataset_ (2017), an anonymized dataset with over three million online grocery orders from more than 200,000 Instacart users. The data are not randomized, however, so be careful not to generalize to broader populations! All the visualizations you'll see are mostly for fun.

Oh! And of course, here's a link to the GitHub [repo](https://github.com/zk2275?tab=repositories) where all the magic happens. This repository houses all the machinery that generates this website, but you can also find a link to my general GitHub account in the navigation bar.